name: Dev CI

on:
  push:
    branches: ['dev']

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: dev-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test with coverage (fails if < 70%)
        run: npm run test:ci

  open-pr:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ needs.test.result == 'success' }}
    steps:
      - name: Open PR dev -> main if not exists
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_POKE }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const head = 'dev';
            const base = 'main';

            // Check if there's already an open PR from dev to main
            const prs = await github.rest.pulls.list({
              owner, repo, state: 'open', head: `${owner}:${head}`, base
            });
            if (prs.data.length > 0) {
              core.info('PR already exists. Skipping creation.');
              return;
            }

            const pr = await github.rest.pulls.create({
              owner, repo,
              title: 'Promote dev to main',
              head, base,
              body: 'Automated PR: tests passed and coverage >= 70%.'
            });
            core.info(`PR created: ${pr.data.html_url}`);